# Workflow for deploying the build directory to GitHub Pages
name: Deploy build directory to Pages

on:
  # Runs on pushes to the default branch (change 'master' if needed)
  push:
    branches: ["master"]

  # Manual trigger from the Actions tab
  workflow_dispatch:

# Permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Only one concurrent deployment allowed
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload build directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'  # Use the build directory here

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
